$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $true

$env:GOTOOLCHAIN = 'go1.25.12'

go fmt ./...
go test ./...
go test -race ./...
go vet ./...

if (Get-Command govulncheck -ErrorAction SilentlyContinue) {
    govulncheck ./...
} else {
    throw 'govulncheck未安装，安全验证不得跳过。'
}
